#!/bin/sh

# link vim files and install plugins
BASEDIR="$(cd "$( dirname "$0")" && pwd)"
mkdir -p ~/.config/nvim
ln -sf $BASEDIR/init.lua ~/.config/nvim/init.lua
ln -sf $BASEDIR/lua ~/.config/nvim/lua
